@echo off
 
if not exist "vs2022x64.rel_deb.ms" (
    mkdir "vs2022x64.rel_deb.ms"
)

cmake -E chdir "vs2022x64.rel_deb.ms" cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="/MP /bigobj" -DWIN32=1 ^
    -DOS_FOLDER=1 -DENABLE_TESTS=0 -DENABLE_SAMPLES=1 -DENABLE_OPENCV=0 -DENABLE_DOCS=0 ^
    -DENABLE_TEMPLATE=0 -DENABLE_INTEL_GPU=1 -DENABLE_INTEL_NPU=0 -DENABLE_AUTO=0 -DENABLE_MULTI=0 -DENABLE_AUTO_BATCH=0 -DENABLE_HETERO=0 -DVERBOSE_BUILD=0 ^
    -DENABLE_OV_ONNX_FRONTEND=0 -DENABLE_OV_PADDLE_FRONTEND=0 -DPADDLEDET_RESULT=0 -DENABLE_OV_TF_FRONTEND=0 -DENABLE_OV_PYTORCH_FRONTEND=0 -DENABLE_OV_JAX_FRONTEND=0 ^
    -DENABLE_PYTHON=0 -DENABLE_DEBUG_CAPS=1 -DENABLE_CPU_DEBUG_CAPS=1 -DENABLE_NCC_STYLE=0 -DENABLE_CPPLINT=0 ^
    -DTHREADING=TBB -DENABLE_SANITIZER=0 -DENABLE_PROFILING_ITT=0 ^
    -DENABLE_CPU_SUBSET_TESTS_PATH="shared_tests_instances/behavior/compiled_model/model_cache.cpp" ..

pause
