name: 'OpenVINO provider'
description: 'Provides OpenVINO build artifacts from a requested source'
inputs:
  revision:
    description: 'Version of OpenVINO to provide - latest_available | HEAD | specific commit hash'
    required: true
  branch_name:
    description: 'Branch of OpenVINO to take the revision from if no specific hash was provided. 
                  Taken from github context by default'
    required: false
  ov_artifact_name:
    description: "Name under which to upload provided OpenVINO build artifacts, set automatically by default"
    required: false
  commit_packages_to_provide:
    description: "Comma-separated list of OpenVINO packages from post-commit to provide ('all' to get everything)"
    required: false
  commit_build_key:
    description: 'public_linux_ubuntu_20_04_release | public_linux_ubuntu_22_04_release | 
                  public_linux_ubuntu_24_04_release | public_windows_vs2019_release'
    required: false
  commit_share_path:
    description: 'Path to share holding OpenVINO post-commit artifacts'
    required: false
    default: '/mount/build-artifacts'
  nightly_build_key:
    description: 'centos7_x86_64 | debian9_armhf | rhel8_x86_64 | ubuntu20_arm64 | ubuntu20_x86_64 | ubuntu22_x86_64 | 
                  ubuntu24_x86_64 | macos_12_6_arm64 | macos_12_6_x86_64 | windows_x86_64'
    required: false
  nightly_package_source:
    description: 'Source URL hosting OpenVINO nightly archives'
    required: false
    default: 'https://storage.openvinotoolkit.org/repositories/openvino/packages/nightly/latest.json'
  nightly_pip_extra_url:
    description: 'Source URL hosting OpenVINO nightly wheels, for passing to pip as --extra-index-url'
    required: false
    default: 'https://storage.openvinotoolkit.org/simple/wheels/nightly'
outputs:
  ov_artifact_name:
    description: "Name of the artifact to upload OpenVINO build artifacts under"
    value: ${{ steps.openvino_nightly_download.outputs.ov_artifact_name || steps.openvino_commit_output.outputs.ov_artifact_name }}
  ov_package_path:
    description: "Path to OpenVINO core package relative to the root of uploaded artifacts"
    value: ${{ steps.openvino_nightly_download.outputs.ov_package_path || steps.openvino_commit_output.outputs.ov_package_path }}
  ov_wheel_input:
    description: "Input for pip to install OpenVINO python wheel"
    value: ${{ steps.openvino_nightly_wheel.outputs.ov_wheel_input || steps.openvino_commit_wheel.outputs.ov_wheel_input }}
  ov_wheel_source:
    description: "Pip option for custom OV wheel location (--find-links or --extra-index-url)"
    value: ${{ steps.openvino_nightly_wheel.outputs.ov_wheel_source || steps.openvino_commit_wheel.outputs.ov_wheel_source }}

runs:
  using: "composite"
  steps:
    - name: Verify parameters
      if: ${{ !inputs.nightly_build_key && !inputs.commit_build_key || inputs.nightly_build_key && inputs.commit_build_key }}
      shell: bash
      run: |
        echo "Please, set one parameter for action - nightly_build_key or commit_build_key"
        exit 1

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: 'openvinotoolkit/openvino'
        ref: ${{ inputs.branch_name || github.base_ref || github.event.merge_group.base_ref || github.ref }}
        sparse-checkout: .github/actions

    # --- Post-commit case ---
    - name: Clone OpenVINO to get HEAD commit
      if: inputs.revision == 'HEAD'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: 'openvinotoolkit/openvino'
        path: 'openvino'
        ref: ${{ inputs.branch_name || github.base_ref || github.event.merge_group.base_ref || github.ref }}

    - name: Get OpenVINO HEAD commit
      id: get_openvino_head_commit
      if: inputs.revision == 'HEAD'
      shell: bash
      run: |
        head=$(git -C openvino rev-parse HEAD)
        echo "head=$head" >> $GITHUB_OUTPUT

    - name: Download post-commit OpenVINO archives
      id: openvino_commit_download
      if: inputs.commit_build_key
      uses: ./.github/actions/restore_artifacts
      with:
        storage_dir: ${{ inputs.commit_build_key }}
        storage_root: ${{ inputs.commit_share_path }}
        event_name: "commit"
        trigger_repo_sha: ${{ env.OV_REVISION }}
        branch_name: ${{ inputs.branch_name }}
        artifacts_key: ${{ inputs.ov_artifact_name || inputs.commit_build_key }}
        to_restore: ${{ inputs.commit_packages_to_provide }}
      env:
        OV_REVISION: ${{ inputs.revision == 'HEAD' && steps.get_openvino_head_commit.outputs.head || inputs.revision }}

    - name: Set action outputs
      id: openvino_commit_output
      if: steps.openvino_commit_download.outcome == 'success'
      shell: bash
      run: |
        ov_artifact_name=${{ inputs.ov_artifact_name || steps.openvino_commit_download.outputs.restored_artifacts_key }}
        cd ${{ steps.openvino_commit_download.outputs.artifacts_workspace_path }}
        ov_package_path=$(find . -name 'openvino_package*' -printf "%P\n" -quit)
        [ -z "$ov_package_path" ] && echo "No openvino_package found in restored artifacts" && exit 1
        echo "ov_artifact_name=$ov_artifact_name" >> $GITHUB_OUTPUT
        echo "ov_package_path=$ov_package_path" >> $GITHUB_OUTPUT

    - name: Get commit wheel
      id: openvino_commit_wheel
      if: steps.openvino_commit_download.outcome == 'success'
      shell: bash
      run: |
        cd ${{ steps.openvino_commit_download.outputs.artifacts_workspace_path }}
        version=$(yq eval '.components.dldt.custom_params.wheel_product_version' manifest.yml)
        wheel_path=${{ steps.openvino_commit_output.outputs.ov_package_path }}/tools
        default_find_links_cmd="--find-links=./$wheel_path"
        find_links_cmd=$([[ -n "$PIP_FIND_LINKS" ]] && echo "" || echo "$default_find_links_cmd")
        wheel_input="$find_links_cmd openvino==$version"
        echo "ov_wheel_input=$wheel_input" >> $GITHUB_OUTPUT
        echo "ov_wheel_source=$default_find_links_cmd" >> $GITHUB_OUTPUT


    # --- Nightly case ---
    - name: Verify nightly parameters
      if: inputs.nightly_build_key && inputs.revision != 'latest_available'
      shell: bash
      run: |
        echo "Nightly build source provides only 'latest' artifacts, specific revision not yet supported"
        exit 1

    - name: Download nightly OpenVINO archives
      id: openvino_nightly_download
      if: inputs.nightly_build_key
      shell: bash
      run: |
        ov_package_url=$(curl -s ${{ inputs.nightly_package_source }} | jq -r '.${{ inputs.nightly_build_key }}')
        package_basename=$(basename $ov_package_url)
        wget $ov_package_url --progress=bar:force:noscroll -O $package_basename
        package_folder=${package_basename%.*} && mkdir $package_folder
        [[ "$package_basename" == *.zip ]] && unzip "$package_basename" -d $package_folder || tar -xvf "$package_basename" -C $package_folder
        ov_artifact_name=$([ ${{ inputs.ov_artifact_name }} ] && echo ${{ inputs.ov_artifact_name }} || echo $package_folder)
        echo "ov_artifact_name=$ov_artifact_name" >> $GITHUB_OUTPUT
        echo "ov_package_path=$package_folder" >> $GITHUB_OUTPUT

    - name: Upload nightly OpenVINO archives
      if: steps.openvino_nightly_download.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.openvino_nightly_download.outputs.ov_artifact_name }}
        path: ${{ steps.openvino_nightly_download.outputs.ov_package_path }}
        if-no-files-found: 'error'

    - name: Get nightly wheel
      id: openvino_nightly_wheel
      if: steps.openvino_nightly_download.outcome == 'success'
      shell: bash
      run: |
        version=$(echo ${{ steps.openvino_nightly_download.outputs.ov_package_path }} |
          grep -oP '(?<=_)\d{4}\.\d\.\d\.dev\d{8}(?=_)')
        extra_index="--pre --extra-index-url ${{ inputs.nightly_pip_extra_url }}"
        wheel_input="$extra_index openvino==$version"
        echo "ov_wheel_input=$wheel_input" >> $GITHUB_OUTPUT
        echo "ov_wheel_source=$extra_index" >> $GITHUB_OUTPUT
